accounts/urls.py
# from .views import SignUpView #register
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    # path('signup/', SignUpView.as_view(), name='signup'),
    path('oauth/', include('social_django.urls', namespace='social:begin')),
    path('register/', views.register_request, name='register')
]

complainer/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from naijacomplainer import views
from django.conf.urls.static import static
from django.conf import settings
# from accounts import views as account_views
from naijacomplainer.views import HomeView, ComplaintsView, ComplaintSearchView, get_data, ChartData, ChartData2, ChartData3, PieChartView, AreaChartView, BarChartView, UserDelete
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('emp', views.emp, name="index2"),
    path('login/login/accounts/', include('accounts.urls')),
    path('login/login/accounts/', include('django.contrib.auth.urls')),
    path('login/', include('django.contrib.auth.urls')),
    # path('oauth/', include('social_django.urls')),
    path('login/', include('social_django.urls')),
    # path('login/login/accounts/', include('social_django.urls')),
    # path('login/login/accounts/oauth/', include('accounts.urls')),
    path('index2/', views.emp, name="index2"),
    # path('dashboard/', views.dashboard),
    path('success/', views.success, name='success'),
    path("images/<int:id>", views.images, name="images"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.destroy, name="delete"),
    path('<int:pk>/delete', UserDelete.as_view(), name='user_confirm_delete'),
    path('termsofuse/', views.termsofuse, name='terms'),
    path('contactus/', views.contactus, name='contact'),
    path('search/', include('naijacomplainer.urls'), name="search"),
    # path('success/chart/filter-options/', views.get_filter_options, name='chart-filter-options'),
    path('success/chart/', HomeView.as_view(), name='chart'),
    path('complaintsummary/', ComplaintsView.as_view(), name='complaintsummary'),
    path('search/', ComplaintSearchView.as_view(), name="search"),
    path("pie/", csrf_exempt(PieChartView.as_view()), name="pie_chart"),
    path("area/", AreaChartView.as_view(), name="area_chart"),
    path("bar/", BarChartView.as_view(), name="bar_chart"),
    # path, ('success/chart/complaints/<int:year>/', views.get_complaints_chart, name='chart-complaints'),
    path('api/data/', get_data, name='api-data'),
    path('api/chart/data', ChartData.as_view(), name='chartdata'),
    path('api/chart2/data2', ChartData2.as_view(), name='chartdata2'),
    path('api/chart3/data3', ChartData3.as_view(), name='chartdata3'),
    path('upload/', views.image_upload_view, name='upload'),
    # path('map/', views.map, name='map'),
    # path("search/", include("naijacomplainer.urls"), namespace=)
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

naijacomplainer/urls.py
from django.urls import path  
from naijacomplainer import views as response_views
from .views import (searchposts)


app_name = "naijacomplainer"
urlpatterns = [
    path('', response_views.index),
    path('index2/', response_views.emp),
    path('dashboard/', response_views.dashboard),
    path('search/', searchposts, name='searchposts'),

      
]

naijacomplainer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Complainer(models.Model): 
    STATES = (
        ('Abia', 'Abia'),
        ('Abuja', 'Abuja'),
        ('Adamawa', 'Adamawa'),
        ('Akwa-Ibom', 'Akwa-Ibom'),
        ('Anambra', 'Anambra'),
        ('Bauchi', 'Bauchi'),
        ('Bayelsa', 'Bayelsa'),
        ('Benue', 'Benue'),
        ('Borno', 'Borno'),
        ('Cross-River', 'Cross-River'),
        ('Delta', 'Delta'),
        ('Ebonyi', 'Ebonyi'),
        ('Edo', 'Edo'),
        ('Ekiti', 'Ekiti'),
        ('Enugu', 'Enugu'),
        ('Gombe', 'Gombe'),
        ('Imo', 'Imo'),
        ('Jigawa', 'Jigawa'),
        ('Kaduna', 'Kaduna'),
        ('Kano', 'Kano'),
        ('Katsina', 'Katsina'),
        ('Kebbi', 'Kebbi'),
        ('Kogi', 'Kogi'),
        ('Kwara', 'Kwara'),
        ('Lagos', 'Lagos'),
        ('Nasarawa', 'Nasarawa'),
        ('Niger', 'Niger'),
        ('Ogun', 'Ogun'),
        ('Ondo', 'Ondo'),
        ('Osun', 'Osun'),
        ('Oyo', 'Oyo'),
        ('Plateau', 'Plateau'),
        ('Rivers', 'Rivers'),
        ('Sokoto', 'Sokoto'),
        ('Taraba', 'Taraba'),
        ('Yobe', 'Yobe'),
        ('Zamfara', 'Zamfara')
  )
    SECTOR = (
       ('Federal Government', 'Federal Government'),
       ('State Government', 'State Government'),
       ('Local Government', 'Local Government'),
       ('Private Company', 'Private Company'),
       ('Public Company', 'Public Company'),
       ('Other', 'Other'),
   )

    NATURE = (
        ('Delay of Service', 'Delay of Service'),
        ('Non compliance with Regulation', 'Non compliance with Regulation'),
        ('Demand for Bribery', 'Demand for Bribery'),
        ('Vandalism', 'Vandalism'),
        ('Unrepaired or damaged infrastructure', 'Unrepaired or damaged infrastructure '),
        ('Insecurity', 'Insecurity'),
        ('Non Payment of Salary', 'Non Payment of Salary'),
        ('Other', 'Other'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateField(null=True)
    anonymous = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True, null=True)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    state = models.CharField(
        max_length=20, choices=STATES,
        blank=False, null=False)
    complaintIsAgainst = models.CharField(
        max_length=100, choices=SECTOR,
        blank=False, null=True)
    natureOfComplaint = models.CharField(
        max_length=100, choices=NATURE,
        blank=False, null=True)
    complaint = models.TextField(max_length=10000, null=True)
    images = models.ImageField(upload_to='images/', blank=True, null=True)
    videos = models.FileField(upload_to='videos/', blank=True, null=True)

    def __str__(self):
        return self.firstname

    class Meta:  
        db_table = "complainers"
        ordering = ["-id", "-time"]

naijacomplainer/forms.py
from django import forms
from django.forms import ModelForm

from . import models
from .models import Complainer


class ComplainerForm(forms.ModelForm):  
    class Meta:
        model = Complainer
        fields = "__all__"
        # fields = ['user', 'date', 'anonymous', 'firstname', 'lastname', 'state', 'complaintIsAgainst', 'natureOfComplaint', 'complaint', 'images']

# class UploadForm(forms.ModelForm):
#     class Meta:
#         model = Complainer
#         fields = Complainer.images


class DateForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )

naijacomplainer/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from complainer import settings
from django.conf import settings
from .forms import ComplainerForm, DateForm
from .models import Complainer
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import View
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions, status
from django.contrib.auth.models import User
from django.db.models import Count, F, Sum, Avg
from django.db.models.functions import ExtractYear, ExtractMonth
from util.charts import months, get_year_dict
from datetime import datetime
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
import requests

# Create your views here.


BACKGROUND_COLOR = [
    'rgba(255, 99, 132, 0.2)',
    'rgba(54, 162, 235, 0.2)',
    'rgba(255, 206, 86, 0.2)',
    'rgba(75, 192, 192, 0.2)',
    'rgba(153, 102, 255, 0.2)',
    'rgba(255, 159, 64, 0.2)',
    'rgba(256, 100, 14, 0.2)',
    'rgba(55, 163, 236, 0.2)',
    'rgba(257, 207, 87, 0.2)',
    'rgba(76, 193, 193, 0.2)',
    'rgba(154, 103, 256, 0.2)',
    'rgba(256, 160, 65, 0.2)',
    'rgba(257, 101, 133, 0.2)',
    'rgba(56, 164, 237, 0.2)',
    'rgba(258, 208, 88, 0.2)',
    'rgba(77, 194, 194, 0.2)',
    'rgba(155, 104, 257, 0.2)',
    'rgba(259, 160, 66, 0.2)',
    'rgba(260, 104, 134, 0.2)',
    'rgba(57, 166, 239, 0.2)',
    'rgba(260, 210, 88, 0.2)',
    'rgba(77, 196, 194, 0.2)',
    'rgba(156, 106, 259, 0.2)',
    'rgba(261, 161, 67, 0.2)',
    'rgba(262, 102, 134, 0.2)',
    'rgba(59, 166, 240, 0.2)',
    'rgba(263, 208, 88, 0.2)',
    'rgba(79, 198, 194, 0.2)',
    'rgba(159, 108, 260, 0.2)',
    'rgba(265, 161, 66, 0.2)',
    'rgba(268, 102, 136, 0.2)',
    'rgba(60, 168, 241, 0.2)',
    'rgba(270, 210, 90, 0.2)',
    'rgba(80, 200, 196, 0.2)',
    'rgba(160, 104, 264, 0.2)',
    'rgba(272, 211, 65, 0.2)'
]
borderColor = [
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
    'rgba(255, 99, 132, 1)',
    'rgba(54, 162, 235, 1)',
    'rgba(255, 206, 86, 1)',
    'rgba(75, 192, 192, 1)',
    'rgba(153, 102, 255, 1)',
    'rgba(255, 159, 64, 1)',
]
borderWidth = ['1']


@login_required
def emp(request):
    # print(request.POST)
    if request.method == "POST":
        print("POST", request.POST)
        print("FILES", request.FILES)
        form = ComplainerForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            try:
                # print(request)
                # form.save()
                if result['success']:
                    instance = form.save()
                    instance.images = request.FILES.get("images")
                    instance.videos = request.FILES.get("videos")
                    instance.user = request.user
                    instance.save()
                # form.save(user=request.user)
                # return HttpResponse('Complaint successfully submitted')
                # (request, 'index.html', {'form': form})
                # i only added the code below
                # however if you want to use redirect, you have to add it above
                # then change the httpresponse below to redirect
                    messages.success(request, 'New complaint added with success!')
                    return redirect('/success/')
                else:
                    messages.error(request, 'Invalid reCAPTCHA. Please try again.')
                    return redirect('/index2/')
                # ensure you add success to your url
                # eg. path('success/', views.success, name='success'),
            except:
                pass
    elif request.method == "GET":
        form = ComplainerForm(request.GET)
        lists = Complainer.objects.filter(user=request.user)

        query = request.GET.get('q')
        submitbutton = request.GET.get('submit')
        if query is not None:
            try:
                lookups = Q(date__icontains=query) | Q(state__icontains=query) | Q(state=query) | Q(
                    complaintIsAgainst__icontains=query) | Q(natureOfComplaint__icontains=query) | Q(
                    complaint__icontains=query) | Q(firstname__icontains=query) | Q(lastname__icontains=query)
                results = Complainer.objects.filter(lookups, user=request.user).distinct()
                context = {'results': results, 'submitbutton': submitbutton}
                return render(request, 'index2.html', context)
            except:
                return render(request, 'index2.html', {'form': form, 'lists': lists})
        # for list in lists:
        #     print(list.date)
        return render(request, 'index2.html', {'form': form, 'lists': lists})
    else:
        form = ComplainerForm()
        return render(request, 'index2.html', {'form': form, 'lists': lists})


# def employee_detail(request, employee_id):
#     try:
#         employee = Employee.objects.get(id=employee_id)
#     except Employee.DoesNotExist:
#         raise Http404("Employee does not exist")
#     return render(request, 'employee_detail.html', {'employee': employee})

def image_upload_view(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        print("POST", request.POST)
        print("FILES",request.FILES)
        form = ComplainerForm(request.POST, request.FILES)
        lists = Complainer.objects.filter(user=request.user)
        if form.is_valid():
            instance = form.save()
            instance.user = request.user
            instance.save()
            # Get the current instance object to display in the template
            # img_obj = form.instance
            # img_obj = form.instance
            return render(request, 'index2.html', {'form': form, 'lists': lists})
    else:
        form = ComplainerForm()
    return render(request, 'index2.html', {'form': form, 'lists': lists})


def dashboard(request):
    lists = Complainer.objects.all()
    return render(request, "dashboard.html", {'lists': lists})


def edit(request, id):
    complainer = Complainer.objects.get(id=id, user=request.user)
    return render(request, 'edit.html', {'complainer': complainer})


def images(request, id):
    lists = Complainer.objects.get(id=id)
    return render(request, 'images.html', {'lists': lists})


def update(request, id):
    complainer = Complainer.objects.get(id=id, user=request.user)
    form = ComplainerForm(request.POST, instance=complainer)
    # print('update')
    if form.is_valid():
        # print(form)
        # form.save()
        instance = form.save()
        instance.user = request.user
        instance.save()
        return redirect("/index2/")
    # print(form.errors)
    # print(request.POST)
    return render(request, 'edit.html', {'complainer': complainer, 'form': form})


def destroy(request, id):
    complainer = Complainer.objects.get(id=id, user=request.user)
    complainer.delete()
    return redirect("/index2/")


User = get_user_model()


class UserDelete(DeleteView):
    model = User
    # User = Complainer.objects.get()
    success_url = reverse_lazy('login')
    template_name = 'user_confirm_delete.html'


def index(request):
    return render(request, 'index.html')


def success(request):
    return render(request, 'success.html')


def termsofuse(request):
    return render(request, 'termsofuse.html')


def contactus(request):
    return render(request, 'contactus.html')


def complaintsummary(request):
    return render(request, 'complaintsummary.html')


class ComplaintSearchView(View):
    def get(self, request, *args, **kwargs):
        sorted_list_state = Complainer.objects.values("state").annotate(count=Count('state')).order_by('-count')[:5]
        sorted_list_nature = Complainer.objects.values("natureOfComplaint").annotate(count=Count('natureOfComplaint')).order_by('-count')[:5]
        sorted_list_against = Complainer.objects.values("complaintIsAgainst").annotate(count=Count('complaintIsAgainst')).order_by('-count')[:5]

        date_form = DateForm()
        context = {"sorted_list_state": sorted_list_state, "sorted_list_nature": sorted_list_nature, "sorted_list_against": sorted_list_against, "form": date_form}

        print(context)

        return render(request, 'search.html', context)

    def sort_states(self, item):
        return item.get("count")

    def sort_nature(self, item):
        return item.get("count")

    def sort_against(self, item):
        return item.get("count")

    def post(self, request, *args, **kwargs):
        # sorted_list_state = Complainer.objects.values("state").annotate(count=Count('state')).order_by('-count')[:5]

naijacomplainer/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head> {% load static %}
   <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Complain Nigeria-Edit Complaint</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/fonts/icomoon/style.css">
    <link rel="stylesheet" href="/static/css2/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css2/style.css">
    <link rel="stylesheet" href="/static/css2/bootstrap.min.css">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
<style>
    *{margin-top: 0px !important;}
    #three:hover {color:black !important;}
    .one {text-shadow: 2px 2px white;}
     .four:hover{
        color: black !important;
        }
</style>
</head>
<body>

<div class="container-fluid" style="background-image: url('/static/images/ovinuchi-ejiohuo-OxesnxkySD0-unsplash.jpg');background-size:100% 100%;">
      <div>Hi {{ user.username }}!</div>
      <div><a href="{% url 'index2' %}" style="text-decoration:none;color:green;" class="four">Back</a></div>
      <div><a href="{% url 'logout' %}" style="text-decoration:none;color:green;" class="four">Log Out</a></div>
<!--    <div class="bg order-1 order-md-2" style="background-image: url('/static/images/bg_1.jpg');"></div>-->
        <div class="contents">
            <div class="container d-flex align-items-center justify-content-center">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-block" style="background:transparent !important;"> <!--style="width:190vw"-->
                            <div class="text-center mb-5">
                                <h3>Welcome {{ user.username }}, please make your update.</h3>
                            </div>
<!--                            {% if form.errors %}-->
<!--    {% for field in form %}-->
<!--        {% for error in field.errors %}-->
<!--            <div class="alert alert-danger">-->
<!--                <strong>{{ error|escape }}</strong>-->
<!--            </div>-->
<!--        {% endfor %}-->
<!--    {% endfor %}-->
<!--    {% for error in form.non_field_errors %}-->
<!--        <div class="alert alert-danger">-->
<!--            <strong>{{ error|escape }}</strong>-->
<!--        </div>-->
<!--    {% endfor %}-->
<!--{% endif %}-->
<!--                            <form method="POST" action="/update/{{complainer.id}}">-->
                                <form method="POST" action="{% url 'update' complainer.id %}">
                                {% csrf_token %}
                            <div class="form-group first">
                            <label class="col-sm-2 col-form-label" ><b>Date:</b></label>
                                <input type="date" name="date" required id="id_date" class="form-control" placeholder="Date format: Year-Month-Date E.g:2021-01-01" value="{{ complainer.date }} (Date format: Year-Month-Date)">
                            <!--    <div class="col-sm-4">-->
<!--                            {{ form.date }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-8 col-form-label" ><b>Hide First and Last Name:</b></label>
                                  <input type="checkbox" name="anonymous" id="id_anonymous">
                            <p style="text-align:center;color:black;">First and Last Name will not show in global search. They will only show here.</p>
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-8 col-form-label"><b>First Name:</b></label>
                                <input type="text" name="firstname" maxlength="100" required id="id_firstname" class="form-control" placeholder="Your Firstname" value="{{ complainer.firstname }}">
<!--                            {{ form.firstname }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-8 col-form-label"><b>Last Name:</b></label>
                                <input type="text" name="lastname" maxlength="100" required id="id_lastname" class="form-control" placeholder="Your Lastname" value="{{ complainer.lastname }}">
<!--                            {{ form.lastname }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-2 col-form-label"><b>State:</b></label>
                                <select name="state" required id="id_state" class="form-control">
  <option value=" " selected>{{ complainer.state }} (Confirm selection in dropdown)</option>

  <option value="Abia">Abia</option>

  <option value="Abuja">Abuja</option>

  <option value="Adamawa">Adamawa</option>

  <option value="Akwa-Ibom">Akwa-Ibom</option>

  <option value="Anambra">Anambra</option>

  <option value="Bauchi">Bauchi</option>

  <option value="Bayelsa">Bayelsa</option>

  <option value="Benue">Benue</option>

  <option value="Borno">Borno</option>

  <option value="Cross-River">Cross-River</option>

  <option value="Delta">Delta</option>

  <option value="Ebonyi">Ebonyi</option>

  <option value="Edo">Edo</option>

  <option value="Ekiti">Ekiti</option>

  <option value="Enugu">Enugu</option>

  <option value="Gombe">Gombe</option>

  <option value="Imo">Imo</option>

  <option value="Jigawa">Jigawa</option>

  <option value="Kaduna">Kaduna</option>

  <option value="Kano">Kano</option>

  <option value="Katsina">Katsina</option>

  <option value="Kebbi">Kebbi</option>

  <option value="Kogi">Kogi</option>

  <option value="Kwara">Kwara</option>

  <option value="Lagos">Lagos</option>

  <option value="Nasarawa">Nasarawa</option>

  <option value="Niger">Niger</option>

  <option value="Ogun">Ogun</option>

  <option value="Ondo">Ondo</option>

  <option value="Osun">Osun</option>

  <option value="Oyo">Oyo</option>

  <option value="Plateau">Plateau</option>

  <option value="Rivers">Rivers</option>

  <option value="Sokoto">Sokoto</option>

  <option value="Taraba">Taraba</option>

  <option value="Yobe">Yobe</option>

  <option value="Zamfara">Zamfara</option>

</select>
<!--                            {{ form.state }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-8 col-form-label one"><b>Complaint is Against:</b></label>
                                <select name="complaintIsAgainst" required id="id_complaintIsAgainst" class="form-control" >
  <option value=" " selected>{{ complainer.complaintIsAgainst }} (Confirm selection in dropdown)</option>

  <option value="Federal Government">Federal Government</option>

  <option value="State Government">State Government</option>

  <option value="Local Government">Local Government</option>

  <option value="Private Company">Private Company</option>

  <option value="Public Company">Public Company</option>

  <option value="Other">Other</option>

</select>
<!--                            {{ form.complaintIsAgainst }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-8 col-form-label one" style="margin-right:20px"><b>Nature of Complaint:</b></label>
                                <select name="natureOfComplaint" required id="id_natureOfComplaint" class="form-control">
  <option value=" " selected>{{ complainer.natureOfComplaint }} (Confirm selection in dropdown)</option>

  <option value="Delay of Service">Delay of Service</option>

  <option value="Non compliance with Regulation">Non compliance with Regulation</option>

  <option value="Demand for Bribery">Demand for Bribery</option>

  <option value="Vandalism">Vandalism</option>

  <option value="Unrepaired or damaged infrastructure">Unrepaired or damaged infrastructure </option>

  <option value="Insecurity">Insecurity</option>

  <option value="Non Payment of Salary">Non Payment of Salary</option>

  <option value="Other">Other</option>

</select>
<!--                            {{ form.natureOfComplaint }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-8 col-form-label one" ><b>Update Complaint:</b></label>
                                <textarea name="complaint" cols="40" rows="10" maxlength="10000" required id="id_complaint" class="form-control" placeholder="Your Complaint" >{{ complainer.complaint }}
</textarea>
<!--                            {{ form.complaint }}-->
                            </div>
                            <div class="form-group last mb-3">
                            <label class="col-sm-1 col-form-label"></label>
                            <button type="submit" class="btn btn-block py-2 btn-primary" style="background-color:darkgreen;border:solid 2px aquamarine;color:white;" id="three">Update</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
<br>

<p><a href="{% url 'logout' %}" style="color:green;" class="four">Log Out</a></p>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

naijacomplainer/templates/user_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Account Delete</title>
</head>
<body>
 {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete your account?</p>
        <input type="submit" value="Confirm">
    </form>
    {% else %}
        <p><a href="{% url 'login' %}">Login</a></p>
    {% endif %}
</body>
</html>